{
    'name' : 'Hospital Management',
    'version' : '12.0.1.0.0',
    'summary': 'Module for managing the Hospitals',
    'sequence': '10',
    'License': 'AGPL-3',
    'author':'Odoo Mates',
    'maintainer' : 'Odoo Mates',
    'category': 'Extra Tools',
    'website': 'odoomates.com',
    'depends': ['sale','base', 'mail','report_xlsx', 'board','web_timeline','muk_web_searchpanel','web_notify','website'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/data.xml',
        'data/cron.xml',
        'data/mail_template.xml',
        'wizards/create_appointment.xml',
        'views/patient.xml',
        'views/doctor.xml',
        'views/appointment.xml',
        'views/lab.xml',
        'views/sale_order.xml',
        'views/server_action.xml',
        'views/settings.xml',
        'views/dashboard.xml',
        # 'views/website_form.xml',
        'reports/patient_card.xml',
        'reports/appointment.xml',
        'reports/report.xml',
        'reports/sale_report_inherit.xml'
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False
}
